name: Upload IPA to App Store Connect

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      # 1️⃣ Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Fastlane kurulumu
      - name: Install fastlane
        run: sudo gem install fastlane

      # 3️⃣ JSON API Key dosyasını oluştur
      - name: Create API key JSON file
        run: |
          mkdir -p fastlane
          echo "${{ secrets.APPSTORE_API_KEY_JSON }}" > fastlane/AuthKey.json

      # 4️⃣ IPA'yı App Store Connect'e yükle
      - name: Upload IPA
        run: |
          fastlane deliver \
            --ipa ./atikkodum.ipa \
            --skip_screenshots \
            --skip_metadata \
            --skip_app_version_update \
            --force \
            --api-key ./fastlane/AuthKey.json
